# Generated by Django 3.2.3 on 2021-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210720_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
